// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpMFb9a_AQUQOmldeCxSJer5WWm0fkbOk',
    appId: '1:717837204692:web:2438175e11d03bd0e8cf41',
    messagingSenderId: '717837204692',
    projectId: 'askly-de21f',
    authDomain: 'askly-de21f.firebaseapp.com',
    databaseURL: 'https://askly-de21f.firebaseio.com',
    storageBucket: 'askly-de21f.appspot.com',
    measurementId: 'G-247S88VBQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUC6qJML1ccCrh7gsFPljsRv2vAtR9zjA',
    appId: '1:717837204692:android:1fecc0819c186aa9e8cf41',
    messagingSenderId: '717837204692',
    projectId: 'askly-de21f',
    databaseURL: 'https://askly-de21f.firebaseio.com',
    storageBucket: 'askly-de21f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4jnTdArfQLgSuCsaTNFigJBi-RmLfbqc',
    appId: '1:717837204692:ios:69557df3c72da0c0e8cf41',
    messagingSenderId: '717837204692',
    projectId: 'askly-de21f',
    databaseURL: 'https://askly-de21f.firebaseio.com',
    storageBucket: 'askly-de21f.appspot.com',
    iosClientId: '717837204692-qatr3pc2e04d2d2ufdm4chp0ij8m8h0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.askly',
  );
}
